tracing: Remove semi-colon after if statement
Fixes the following Clang warning:

../kernel/trace/trace_output.c:1025:28: error: if statement has empty
body [-Werror,-Wempty-body]

Fixes: 6f6f99a38132 ("trace: add non-hierarchical function_graph option")
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>